# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pigs_ui.ui',
# licensing of 'pigs_ui.ui' applies.
#
# Created: Sat Dec  8 16:28:04 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 423))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.participants_verticalLayout = QtWidgets.QVBoxLayout()
        self.participants_verticalLayout.setObjectName("participants_verticalLayout")
        self.verticalLayout.addLayout(self.participants_verticalLayout)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.checkall_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkall_pushButton.setObjectName("checkall_pushButton")
        self.verticalLayout.addWidget(self.checkall_pushButton)
        self.uncheckall_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.uncheckall_pushButton.setObjectName("uncheckall_pushButton")
        self.verticalLayout.addWidget(self.uncheckall_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rounds_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.rounds_lineEdit.setObjectName("rounds_lineEdit")
        self.horizontalLayout.addWidget(self.rounds_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.score_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.score_lineEdit.setObjectName("score_lineEdit")
        self.horizontalLayout_2.addWidget(self.score_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_3.addWidget(self.startButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.output_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output_plainTextEdit.setReadOnly(True)
        self.output_plainTextEdit.setObjectName("output_plainTextEdit")
        self.verticalLayout_2.addWidget(self.output_plainTextEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Pass the Pigs strategy tournament simulator", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Participants:</span></p></body></html>", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>All selected players will play<br/>the others individually on each<br/>round. Players will not play against<br/>themselves.<br/><br/>Hover over a strategy name for<br/>a description.<br/><br/>You can easily try out your own<br/>strategies by editing strategies.py!</p></body></html>", None, -1))
        self.checkall_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Check all", None, -1))
        self.uncheckall_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Uncheck all", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Tournament rounds to play:", None, -1))
        self.rounds_lineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "50", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Score to play to (each game):", None, -1))
        self.score_lineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "100", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Results:", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

